const STORAGE_KEY='pathToOffer.v0.1';
const THEME_KEY='pathToOffer.theme';
const stages=[
  ['discovered','发现'],['wishlist','待投递'],['preparing','准备中'],['applied','已投递'],['assessment','测评'],['interview1','一面'],['interview2','二面'],['interview3','三面/终面'],['hr','HR 面'],['offer','Offer'],['signed','已签约'],['rejected','结束']
];
const palettes=[
  ['Sage','#97b4a7','#668d7b','#e8f0ec'],['Mist Blue','#9db4c5','#66879d','#e9f0f5'],['Dusty Rose','#c7a5a7','#9e7478','#f4eaea'],['Lavender','#b4aac9','#867aa3','#efebf5'],['Oat','#c4b49a','#9b8768','#f3eee5'],['Seafoam','#9ec3bb','#6d9b91','#e8f4f1'],['Clay','#c5a28c','#9f7560','#f5ece6'],['Periwinkle','#a8b1d0','#7883ad','#eceef7'],['Olive Mist','#b1b99a','#858f69','#eff1e8'],['Peach Mist','#d1ad9d','#aa7f6d','#f7ede8']
];
const sample={
 jobs:[
  {id:'j1',company:'示例 · 北辰智能',department:'推理系统',role:'AI Infra / LLM Inference Engineer',location:'北京',salary:'35–50k × 16',direction:'AI Infra',priority:'A',status:'interview1',statusDate:'2026-08-18',url:'',jd:'负责大模型推理系统、KV Cache、分布式并行与性能优化。',resumeVersion:'AI Infra v7.1',prepUrl:'https://github.com/MLliu6/26-27-interview',notes:'准备 vLLM / CUDA / KV Cache 系统设计。',timeline:[{status:'discovered',date:'2026-08-08'},{status:'applied',date:'2026-08-11'},{status:'interview1',date:'2026-08-18'}]},
  {id:'j2',company:'示例 · 云杉芯片',department:'软件栈',role:'AI 芯片软件工程师',location:'上海',salary:'30–45k × 15',direction:'AI Chip',priority:'A',status:'assessment',statusDate:'2026-08-16',url:'',jd:'编译器、算子库与 NPU 性能优化。',resumeVersion:'芯片软件 v7.1',prepUrl:'https://github.com/MLliu6/26-27-interview',notes:'复习算子优化与编译器基础。',timeline:[{status:'discovered',date:'2026-08-09'},{status:'applied',date:'2026-08-12'},{status:'assessment',date:'2026-08-16'}]},
  {id:'j3',company:'示例 · 长河科技',department:'多模态',role:'VLM 推理优化工程师',location:'深圳',salary:'32–48k × 16',direction:'VLM/VLA',priority:'B',status:'preparing',statusDate:'2026-08-15',url:'',jd:'负责 VLM/VLA 推理、量化与端侧部署。',resumeVersion:'私企版 v7.1',prepUrl:'https://github.com/MLliu6/26-27-interview',notes:'补齐视觉 Token 剪枝与 PTQ 项目讲解。',timeline:[{status:'discovered',date:'2026-08-13'},{status:'preparing',date:'2026-08-15'}]},
  {id:'j4',company:'示例 · 京华研究院',department:'智能计算中心',role:'高性能计算研发',location:'北京',salary:'事业单位口径',direction:'央国企/HPC',priority:'B',status:'wishlist',statusDate:'2026-08-14',url:'',jd:'高性能计算、异构加速、人工智能系统。',resumeVersion:'央国企版 v7.1',prepUrl:'',notes:'等待网申开放。',timeline:[{status:'discovered',date:'2026-08-14'},{status:'wishlist',date:'2026-08-14'}]}
 ],
 reviews:[{id:'r1',jobId:'j1',title:'示例 · AI Infra 一面预演',date:'2026-08-14',content:'问题：为什么 PagedAttention 能降低 KV Cache 碎片？\n\n回答框架：从连续显存分配问题、block/page 抽象、逻辑到物理映射、共享与复用讲起。\n\n改进：需要把调度器与 block manager 的边界讲得更清楚。'}],
 resumes:[{name:'私企版 v7.1',note:'AI Infra / 推理系统 / 芯片软件主版本'},{name:'央国企版 v7.1',note:'研究与工程经历表述更完整'}],
 assets:[{name:'26-27-interview · 面试知识库',url:'https://github.com/MLliu6/26-27-interview',note:'项目讲稿、Q&A、证据映射与附录'}],
 discovery:[{id:'d1',company:'示例 · 星海计算',role:'CUDA 性能优化工程师',meta:'北京 · 校招 · 待核验',url:''}]
};
let state=loadState();
let selectedReviewId=state.reviews[0]?.id||null;
let pipelineMode='board';

function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):structuredClone(sample)}catch{return structuredClone(sample)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function stageName(id){return stages.find(s=>s[0]===id)?.[1]||id}
function uid(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`}
function today(){return new Date().toISOString().slice(0,10)}
function fmt(date){if(!date)return '未记录';const d=new Date(`${date}T00:00:00`);return Number.isNaN(d)?date:d.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}

function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function renderMetrics(){const active=state.jobs.filter(j=>!['signed','rejected'].includes(j.status)).length;const interviews=state.jobs.filter(j=>['interview1','interview2','interview3','hr'].includes(j.status)).length;const offers=state.jobs.filter(j=>['offer','signed'].includes(j.status)).length;const reviewed=state.reviews.length;const metrics=[['活跃岗位',active,'仍在推进'],['面试中',interviews,'进入面试流程'],['Offer',offers,'收到 / 已签'],['面经',reviewed,'已沉淀复盘']];document.querySelector('#metricGrid').innerHTML=metrics.map(([k,v,s])=>`<article class="metric"><p class="eyebrow">${k}</p><div class="value">${v}</div><small>${s}</small></article>`).join('')}
function renderMiniPipeline(){const groups=[['发现/准备',['discovered','wishlist','preparing']],['已投递',['applied']],['测评',['assessment']],['面试',['interview1','interview2','interview3','hr']],['Offer',['offer','signed']]];document.querySelector('#miniPipeline').innerHTML=groups.map(([name,ss])=>`<div class="mini-stage"><strong>${state.jobs.filter(j=>ss.includes(j.status)).length}</strong><span>${name}</span></div>`).join('')}
function renderActions(){const order=state.jobs.filter(j=>j.statusDate&&!['signed','rejected'].includes(j.status)).sort((a,b)=>a.statusDate.localeCompare(b.statusDate)).slice(0,5);document.querySelector('#nextActions').innerHTML=order.length?order.map(j=>`<div class="activity"><strong>${esc(j.company)} · ${esc(stageName(j.status))}</strong><small>${fmt(j.statusDate)} · ${esc(j.role)}</small></div>`).join(''):'<div class="empty-state"><p>暂无近期动作</p></div>'}
function renderFunnel(){const rows=[['已发现',state.jobs.length],['已投递',state.jobs.filter(j=>!['discovered','wishlist','preparing'].includes(j.status)).length],['进入面试',state.jobs.filter(j=>['interview1','interview2','interview3','hr','offer','signed'].includes(j.status)).length],['Offer',state.jobs.filter(j=>['offer','signed'].includes(j.status)).length]];const max=Math.max(1,...rows.map(r=>r[1]));document.querySelector('#funnel').innerHTML=rows.map(([n,v])=>`<div class="funnel-row"><span>${n}</span><div class="funnel-track"><div class="funnel-fill" style="width:${v/max*100}%"></div></div><strong>${v}</strong></div>`).join('');document.querySelector('#learningLoop').innerHTML=`<div class="big">${state.reviews.length}</div><p>条结构化面经已进入你的个人知识循环。下一版将从复盘中自动聚类高频题、薄弱知识点和项目追问。</p>`}
function filteredJobs(){const q=(document.querySelector('#searchInput')?.value||'').trim().toLowerCase();const p=document.querySelector('#priorityFilter')?.value||'all';const d=document.querySelector('#directionFilter')?.value||'all';return state.jobs.filter(j=>(p==='all'||j.priority===p)&&(d==='all'||j.direction===d)&&(!q||[j.company,j.role,j.location,j.direction].join(' ').toLowerCase().includes(q)))}
function renderDirectionFilter(){const sel=document.querySelector('#directionFilter');if(!sel)return;const old=sel.value;const dirs=[...new Set(state.jobs.map(j=>j.direction).filter(Boolean))];sel.innerHTML='<option value="all">全部方向</option>'+dirs.map(d=>`<option>${esc(d)}</option>`).join('');sel.value=dirs.includes(old)?old:'all'}
function jobCard(j){return `<article class="job-card" draggable="true" data-job-id="${j.id}"><div class="job-meta"><span class="priority">${esc(j.priority)}</span><span class="date">${fmt(j.statusDate)}</span></div><h3>${esc(j.company)}</h3><p>${esc(j.role)}</p><div class="job-meta"><span class="date">${esc(j.location||'地点待定')}</span><span class="date">${esc(j.direction||'未分类')}</span></div></article>`}
function renderPipeline(){renderDirectionFilter();const jobs=filteredJobs();const kanban=document.querySelector('#kanban');kanban.innerHTML=stages.map(([id,name])=>{const js=jobs.filter(j=>j.status===id);return `<section class="kanban-col" data-stage="${id}"><div class="kanban-head"><strong>${name}</strong><span class="count">${js.length}</span></div><div class="job-stack">${js.map(jobCard).join('')}</div></section>`}).join('');bindDnD();document.querySelector('#jobTableWrap').innerHTML=`<table class="job-table"><thead><tr><th>公司</th><th>岗位</th><th>方向</th><th>状态</th><th>日期</th><th>优先级</th></tr></thead><tbody>${jobs.map(j=>`<tr data-job-id="${j.id}"><td>${esc(j.company)}</td><td>${esc(j.role)}</td><td>${esc(j.direction)}</td><td>${stageName(j.status)}</td><td>${fmt(j.statusDate)}</td><td>${esc(j.priority)}</td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-job-id]').forEach(el=>el.addEventListener('click',e=>{if(!e.defaultPrevented)openJob(el.dataset.jobId)}))}
function bindDnD(){let dragging=null;document.querySelectorAll('.job-card').forEach(card=>{card.addEventListener('dragstart',e=>{dragging=card.dataset.jobId;card.classList.add('dragging');e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>card.classList.remove('dragging'))});document.querySelectorAll('.kanban-col').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='move'});col.addEventListener('drop',e=>{e.preventDefault();if(!dragging)return;const job=state.jobs.find(j=>j.id===dragging);const next=col.dataset.stage;if(job&&job.status!==next){job.status=next;job.statusDate=today();job.timeline=job.timeline||[];job.timeline.push({status:next,date:today()});saveState();toast(`已更新为「${stageName(next)}」`)}})})}
function renderDiscovery(){document.querySelector('#discoveryList').innerHTML=state.discovery.length?state.discovery.map(d=>`<div class="discovery-item"><div><strong>${esc(d.company)}</strong><p>${esc(d.role)}</p><small class="muted">${esc(d.meta||'待判断')}</small></div><button class="btn ghost" data-promote="${d.id}">加入流程</button></div>`).join(''):'<div class="empty-state"><p>暂无待判断岗位</p></div>';document.querySelectorAll('[data-promote]').forEach(b=>b.onclick=()=>promoteDiscovery(b.dataset.promote))}
function renderLibrary(){document.querySelector('#resumeList').innerHTML=state.resumes.map((r,i)=>`<div class="asset-item"><div><strong>${esc(r.name)}</strong><small>${esc(r.note||'')}</small></div><button class="text-btn" data-del-resume="${i}">×</button></div>`).join('');document.querySelector('#assetList').innerHTML=state.assets.map((a,i)=>`<div class="asset-item"><div><strong>${esc(a.name)}</strong><small>${esc(a.note||a.url||'')}</small></div><a class="text-btn" href="${esc(a.url)}" target="_blank" rel="noopener">打开 ↗</a></div>`).join('')}
function renderReviews(){const list=document.querySelector('#reviewList');list.innerHTML=state.reviews.length?state.reviews.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(r=>`<article class="review-card ${r.id===selectedReviewId?'active':''}" data-review-id="${r.id}"><p class="eyebrow">${fmt(r.date)}</p><h3>${esc(r.title)}</h3><small>${r.content.length} 字符</small></article>`).join(''):'<div class="empty-state"><p>还没有面经</p></div>';document.querySelectorAll('[data-review-id]').forEach(c=>c.onclick=()=>{selectedReviewId=c.dataset.reviewId;renderReviews()});const r=state.reviews.find(x=>x.id===selectedReviewId);document.querySelector('#reviewEmpty').classList.toggle('hidden',!!r);const content=document.querySelector('#reviewContent');content.classList.toggle('hidden',!r);if(r){const job=state.jobs.find(j=>j.id===r.jobId);content.innerHTML=`<div class="panel-head"><div><p class="eyebrow">${job?esc(job.company):'INTERVIEW REVIEW'}</p><h2>${esc(r.title)}</h2></div><button class="text-btn" id="deleteReview">删除</button></div><p class="muted">${fmt(r.date)}</p><pre>${esc(r.content)}</pre>`;document.querySelector('#deleteReview').onclick=()=>{state.reviews=state.reviews.filter(x=>x.id!==r.id);selectedReviewId=state.reviews[0]?.id||null;saveState()}}}
function renderAll(){renderMetrics();renderMiniPipeline();renderActions();renderFunnel();renderPipeline();renderDiscovery();renderLibrary();renderReviews()}

function openJob(id){const job=id?state.jobs.find(j=>j.id===id):null;const f=document.querySelector('#jobForm');f.reset();document.querySelector('#drawerTitle').textContent=job?`${job.company} · ${job.role}`:'新增岗位';document.querySelector('#deleteJobBtn').classList.toggle('hidden',!job);[...f.elements].forEach(el=>{if(!el.name)return;el.value=job?.[el.name]??(el.name==='status'?'wishlist':el.name==='statusDate'?today():el.name==='priority'?'B':'')});renderTimeline(job?.timeline||[]);document.querySelector('#jobDrawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open');document.querySelector('#jobDrawer').setAttribute('aria-hidden','false')}
function closeJob(){document.querySelector('#jobDrawer').classList.remove('open');document.querySelector('#drawerBackdrop').classList.remove('open');document.querySelector('#jobDrawer').setAttribute('aria-hidden','true')}
function renderTimeline(items){document.querySelector('#statusTimeline').innerHTML=items.length?items.slice().reverse().map(x=>`<div class="timeline-item"><strong>${stageName(x.status)}</strong><small>${x.date||'未记录日期'}</small></div>`).join(''):'<div class="muted">保存后开始记录状态变化。</div>'}
function saveJob(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());let job=state.jobs.find(j=>j.id===data.id);if(!job){job={...data,id:uid('job'),timeline:[{status:data.status,date:data.statusDate||today()}]};state.jobs.unshift(job)}else{if(job.status!==data.status)job.timeline=[...(job.timeline||[]),{status:data.status,date:data.statusDate||today()}];Object.assign(job,data)}saveState();closeJob();toast('岗位已保存')}
function deleteCurrentJob(){const id=document.querySelector('#jobForm [name=id]').value;if(!id)return;const job=state.jobs.find(j=>j.id===id);if(confirm(`删除 ${job.company} · ${job.role}？`)){state.jobs=state.jobs.filter(j=>j.id!==id);state.reviews=state.reviews.filter(r=>r.jobId!==id);saveState();closeJob();toast('已删除岗位')}}
function promoteDiscovery(id){const d=state.discovery.find(x=>x.id===id);if(!d)return;state.jobs.unshift({id:uid('job'),company:d.company,department:'',role:d.role,location:'',salary:'',direction:'',priority:'B',status:'wishlist',statusDate:today(),url:d.url||'',jd:'',resumeVersion:'',prepUrl:'',notes:'来自发现岗位 Inbox',timeline:[{status:'wishlist',date:today()}]});state.discovery=state.discovery.filter(x=>x.id!==id);saveState();toast('已加入投递流程')}

function openModal(title,html){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=html;document.querySelector('#quickModal').classList.add('open');document.querySelector('#modalBackdrop').classList.add('open')}
function closeModal(){document.querySelector('#quickModal').classList.remove('open');document.querySelector('#modalBackdrop').classList.remove('open')}
function jobPasteModal(){openModal('从链接 / 文本添加岗位',`<form class="quick-form" id="discoveryForm"><label>公司<input name="company" required></label><label>岗位<input name="role" required></label><label>岗位链接<input name="url" type="url"></label><label>来源 / 备注<textarea name="meta" rows="3" placeholder="官网 / OfferJack / 招聘平台…"></textarea></label><button class="btn primary" type="submit">加入发现 Inbox</button></form>`);document.querySelector('#discoveryForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());state.discovery.unshift({...d,id:uid('disc')});saveState();closeModal();toast('已加入发现岗位')}}
function assetModal(){openModal('添加准备资料',`<form class="quick-form" id="assetForm"><label>名称<input name="name" required></label><label>链接<input name="url" type="url" required></label><label>说明<input name="note"></label><button class="btn primary" type="submit">保存资料</button></form>`);document.querySelector('#assetForm').onsubmit=e=>{e.preventDefault();state.assets.unshift(Object.fromEntries(new FormData(e.currentTarget).entries()));saveState();closeModal();toast('资料链接已保存')}}
async function importReview(file){if(!file)return;let text='';try{if(file.name.toLowerCase().endsWith('.docx')){if(!window.mammoth)throw new Error('DOCX 解析器尚未加载');const ab=await file.arrayBuffer();text=(await window.mammoth.extractRawText({arrayBuffer:ab})).value}else{text=await file.text()}const id=uid('review');state.reviews.unshift({id,jobId:'',title:file.name.replace(/\.(txt|docx)$/i,''),date:today(),content:text.trim()});selectedReviewId=id;saveState();switchView('reviews');toast('面经已导入')}catch(err){toast(`导入失败：${err.message}`)}}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`path-to-offer-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('已导出本地数据')}
function applyTheme(hex,strong,soft){document.documentElement.style.setProperty('--accent',hex);document.documentElement.style.setProperty('--accent-strong',strong);document.documentElement.style.setProperty('--accent-soft',soft)}
function initTheme(){const saved=JSON.parse(localStorage.getItem(THEME_KEY)||'null');if(saved)applyTheme(...saved);const sw=document.querySelector('#swatches');sw.innerHTML=palettes.map((p,i)=>`<button class="swatch" title="${p[0]}" data-theme="${i}" style="background:${p[1]}"></button>`).join('');sw.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{const p=palettes[+b.dataset.theme];applyTheme(p[1],p[2],p[3]);localStorage.setItem(THEME_KEY,JSON.stringify(p.slice(1)));document.querySelector('#themePopover').classList.remove('open');toast(`主题：${p[0]}`)})}

function init(){document.querySelector('#statusSelect').innerHTML=stages.map(([id,n])=>`<option value="${id}">${n}</option>`).join('');document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('[data-go]').forEach(n=>n.onclick=()=>switchView(n.dataset.go));document.querySelector('#addJobBtn').onclick=()=>openJob();document.querySelector('#closeDrawer').onclick=closeJob;document.querySelector('#cancelJobBtn').onclick=closeJob;document.querySelector('#drawerBackdrop').onclick=closeJob;document.querySelector('#jobForm').onsubmit=saveJob;document.querySelector('#deleteJobBtn').onclick=deleteCurrentJob;document.querySelector('#exportBtn').onclick=exportData;document.querySelector('#openOfferJack').onclick=()=>window.open('https://www.offerjack.cn/','_blank','noopener');document.querySelector('#pasteJobBtn').onclick=jobPasteModal;document.querySelector('#addAssetBtn').onclick=assetModal;document.querySelector('#reviewImport').onchange=e=>{importReview(e.target.files[0]);e.target.value=''};document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#modalBackdrop').onclick=closeModal;document.querySelector('#themeBtn').onclick=e=>{e.stopPropagation();document.querySelector('#themePopover').classList.toggle('open')};document.addEventListener('click',e=>{if(!e.target.closest('#themePopover')&&!e.target.closest('#themeBtn'))document.querySelector('#themePopover').classList.remove('open')});document.querySelectorAll('[data-pipeline-mode]').forEach(b=>b.onclick=()=>{pipelineMode=b.dataset.pipelineMode;document.querySelectorAll('[data-pipeline-mode]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#kanban').classList.toggle('hidden',pipelineMode!=='board');document.querySelector('#jobTableWrap').classList.toggle('hidden',pipelineMode!=='table')});['searchInput','priorityFilter','directionFilter'].forEach(id=>document.querySelector(`#${id}`).addEventListener(id==='searchInput'?'input':'change',renderPipeline));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeJob();closeModal()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();switchView('pipeline');document.querySelector('#searchInput').focus()}});initTheme();renderAll()}
document.addEventListener('DOMContentLoaded',init);