import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../workspace-core-v15.js');
const one={c:'快手',r:'推理工程师',l:'北京',z:'id1',s:'direct-official:test',u:'https://a.test/#/job/id1'};
const two={...one,z:'id2',u:'https://a.test/#/job/id2'};
assert.equal(C.mergeJobs([one,two]).length,2);
assert.notEqual(C.canonicalUrl(one.u),C.canonicalUrl(two.u));
const lead={...one,s:'curated-target:20260903',q:6,d:'pending'};
assert.equal(C.mergeJobs([lead],[one])[0].s,'direct-official:test');
assert.equal(C.isLead(lead),true);assert.equal(C.official(lead),false);
assert.equal(C.official(one),true);
assert.equal(C.canonicalUrl('https://a.test/p?utm_source=x&jobId=123'),'https://a.test/p?jobId=123');
assert.equal(C.company({c:'千寻智能 Spirit AI'}),C.company({c:'千寻智能'}));
const job={id:'a',status:'applied',timeline:[{status:'applied',date:'2026-09-01'}],notes:'keep',custom:{secret:'not exported'},resumeVersion:'v7'};
const next=C.updateStatus(job,'interview1','2026-09-08','通知一面','2026-09-10');
assert.equal(next.timeline.length,2);assert.equal(job.timeline.length,1);assert.equal(next.notes,'keep');assert.equal(next.resumeVersion,'v7');assert.deepEqual(next.custom,job.custom);
assert.equal(C.summary([next],'2026-09-11').due,1);
assert.equal(C.summary([{...next,status:'rejected'}],'2026-09-11').due,0);
assert.throws(()=>C.updateStatus(job,'interview1','bad'));
console.log('v1.5 data/identity/status rules: PASS');
